#11 Render Code with Code Blocks
rucio/documentation pull request #16
Opened 2020-12-11 13:29 UTC by palakyadav1807

Update the Markdown Quote-Blocks used to display code on the website to Code-Blocks for better support and accessibility.

- Made changes in `.md` files to change Block quotes to code blocks.
- Added a folder `prism` inside  `website/static` and added `prism.js` and `prism.css` inside `prism` folder.
- Linked `prism.js` and `prism.css` files to html using `siteConfig.js`.
- Used [prismjs.com](url) for code highlighting.

2020-12-11 13:41 UTC, viveknigam3003 commented on docs/developing.md
> +rucio rule-info <rule-id>
Please add a prefix like a `$` sign when there are multiple commands in a code-block

2020-12-11 13:47 UTC, viveknigam3003 requested changes
Please look at the suggestions and fix them in subsequent commits. The rest looks good to me! ✌🏻

2020-12-11 13:47 UTC, viveknigam3003 commented on docs/installing_server.md
> +```
This is not a bash syntax. This is a cfg file which can be highlighted as plain text

2020-12-11 13:47 UTC, viveknigam3003 commented on docs/installing_server.md
> +```
Same with this

2020-12-11 13:47 UTC, viveknigam3003 commented on docs/rest.md
>  ...
This is JSON and can be highlighted with `json` or `js` tags

2020-12-11 13:47 UTC, viveknigam3003 commented on docs/rse_expressions.md
> +A\\B COMPLEMENT A complement B cloud=ES\\type=SCRATCHDISK
Please review this table and check if it renders correctly

2020-12-11 13:47 UTC, viveknigam3003 commented on docs/setting-up-demo.md
> +```
Add `$` prefix

2020-12-11 13:49 UTC, viveknigam3003 commented
@divya-mohan0209 please review this PR. Although the last PR #13 isn't merged, so this one may show those files changed as well.

2020-12-12 10:57 UTC, viveknigam3003 commented on docs/developing.md
> +$rucio rule-info <rule-id>
Spaces after `$` prefix :/

2020-12-12 10:58 UTC, viveknigam3003 requested changes
Just a very minute change in `developing.md`

2020-12-12 11:01 UTC, palakyadav1807 commented on docs/developing.md
> +$rucio rule-info <rule-id>
Okay removing spaces

2020-12-12 11:51 UTC, viveknigam3003 approved these changes
LGTM 👍

2020-12-12 11:52 UTC, viveknigam3003 approved these changes

2020-12-12 12:00 UTC, viveknigam3003 commented
@divya-mohan0209 I provided my review and the changes have been made. If you may please review it so that this PR may be merged and #11 is closed.

2020-12-12 12:23 UTC, divya-mohan0209 requested changes
Please make these changes. Once done, shall approve them on Monday.

2020-12-12 12:23 UTC, divya-mohan0209 commented on docs/using-rucio-client.md
>  If you\'re running a multi-VO instance of Rucio, then the VO to
Can we please remove the \ in between you and re here?

2020-12-12 12:23 UTC, divya-mohan0209 commented on docs/using-rucio-client.md
> +`--oidc-issuer=<IdP nickname` option (where IdP nickname is the key
`--oidc-issuer=<IdP nickname>` was right. Please include the > at the end.

2020-12-12 12:23 UTC, divya-mohan0209 commented on docs/using-rucio-client.md
>  can be configured with the following parameters in the \[client\]
\[client\] needs to be rewritten as client.

2020-12-12 12:23 UTC, divya-mohan0209 commented on docs/using-rucio-client.md
> +- the identity of the token ("SUB=<user sub claim, ISS=<issuer url") is assigned to an existing Rucio account (pre-provisioned)
This sentence should read as:

the identity of the token ("SUB=<user sub claim>, ISS=<issuer url>") is assigned to an existing Rucio account (pre-provisioned)

2020-12-12 12:23 UTC, divya-mohan0209 commented on docs/using-rucio-client.md
>  `[client]` section of the rucio.cfg file. Rucio Client will then store
`[client]` needs to be rewritten as client

2020-12-12 12:23 UTC, divya-mohan0209 commented on docs/using-rucio-client.md
>  and search for user\'s token saved in such file:
Kindly remove the \ in user's.

2020-12-12 12:23 UTC, divya-mohan0209 commented on docs/using-rucio-client.md
> +```bash
This is not expected to be bash. The rucio.cfg is a file & these can be just code-blocks.

2020-12-12 12:25 UTC, divya-mohan0209 commented on docs/using-rucio-client.md
>  can be configured with the following parameters in the \[client\]
Also, 

rucio -a=<rucio_account_name -S=OIDC --oidc-scope="openid profile offline_access" --oidc-refresh-lifetime=24 -v whoami

needs to read as

rucio -a=<rucio_account_name> -S=OIDC --oidc-scope="openid profile offline_access" --oidc-refresh-lifetime=24 -v whoami

2020-12-14 05:14 UTC, divya-mohan0209 approved these changes
LGTM

2020-12-14 05:14 UTC, merged