doc: added deletion overview with very high level chart. #288
rucio/documentation pull request #295
Opened 2024-03-14 14:22 UTC by panta-123

Added the deletion overveiw in different chapter.

Few things I am not clear.
1. When setting TOMBSTONE by cleaner and undertaker , what is the value it sets. I look through the code and not clear to me.

2. The chart are very crude and may need some imporvement suggestion needed here.

2024-04-10 17:47 UTC, panta-123 commented
All the comments has been resolved !!

2024-06-07 11:10 UTC, bari12 requested changes
Just one more change :-)

2024-06-07 11:10 UTC, bari12 commented on docs/started/concepts/deletion_overview.md
> +After the tombstone is set for replicas, the actual data deletion is done by the `Repear` daemon. The reaper physically deletes the tombstoned replicas from storage.
Change `repear` to `reaper`

2024-08-12 14:12 UTC, voetberg commented on website/static/img/Undertaker-undertaker.png
Can you make the bottom left box a little larger? The a., b., c., tangent-ing with the box edge makes it harder to read.

2024-08-12 14:15 UTC, voetberg commented on website/static/img/Repear-repear.png
Spelling: obsolete not obsolote, and Reaper not repear (see Martin's above comment). The two triangle boxes should be enlarged to make sure the text doesn't escape them.

2024-11-20 12:18 UTC, bari12 commented
It's good. Thanks @panta-123 and @voetberg 
You need to add the file to the sidebars.json though, otherwise it won't show up in the doc

2024-11-20 12:20 UTC, rdimaio commented on docs/started/concepts/deletion_overview.md
> +    Each rule has a corresponding lifetime associated with it (default is None). The attribute `expires at` of the rule is the time when the lifetime is set plus the lifetime associated with rule.
```suggestion
    Each rule has a corresponding lifetime associated with it (default is None). The attribute `expires_at` of the rule is the time when the lifetime is set plus the lifetime associated with the rule.
```

2024-11-20 12:21 UTC, rdimaio commented on docs/started/concepts/deletion_overview.md
> +Deletion in rucio can be performed in broadly two ways.
```suggestion
Deletion in Rucio can be performed in broadly two ways.
```

2024-11-20 12:22 UTC, rdimaio commented on docs/started/concepts/deletion_overview.md
> +    The `Undertaker` daemon is responsible for handling expired dids. The daemon checks if none of the associated rules to the did are locked, if not it removes all rules of the did (see section abov
```suggestion
    The `Undertaker` daemon is responsible for handling expired DIDs. The daemon checks if none of the associated rules to the DID are locked, if not it removes all rules of the DID (see section above). The DID itself is then removed from the catalog.
```

2024-11-20 12:22 UTC, rdimaio commented on docs/started/concepts/deletion_overview.md
> +**The did expiration overrules the rule expiration. But the locked rules are protected.**
```suggestion
**The DID expiration overrules the rule expiration. But the locked rules are protected.**
```

2024-11-20 12:23 UTC, rdimaio commented on docs/started/concepts/deletion_overview.md
> +    The reaper daemon gets all the replicas with tombstone in the RSE and immediately delete all replicas.
```suggestion
    The reaper daemon gets all the replicas with tombstone in the RSE and immediately deletes all replicas. 
```

2024-11-20 12:23 UTC, rdimaio commented on docs/started/concepts/deletion_overview.md
> +    The reaper daemon first check if the free space is needed in the RSE. The needed free space is the difference of minimum free space (attrribute set for RSE) and actual free space in RSE. Deletion
```suggestion
    The reaper daemon first checks if the free space is needed in the RSE. The needed free space is the difference of minimum free space (attrribute set for RSE) and actual free space in RSE. Deletion only occurs once free space is needed.
```

2024-11-20 12:25 UTC, rdimaio commented on website/static/img/Judge-cleaner.png
nit: all other filenames in this asset folder are lowercase; for consistency, this could be renamed to `judge-cleaner.png`

2024-11-20 12:30 UTC, rdimaio reviewed
In case future changes need to be done, it would be great to have the source code for the flowcharts as part of the documentation repo. Maybe we could use Mermaid.js to handle this?

2025-01-24 15:02 UTC, panta-123 commented on website/static/img/reaper.png
There is another step for needed_free_space so that will complicate things if pointrd to single blocks.

2025-01-24 15:03 UTC, panta-123 commented on website/static/img/reaper.png
@rdimaio , The mermaid.js lets create another issue and handle all the chart there.

2025-03-25 20:23 UTC, voetberg commented
Hi @panta-123 , sorry it took me this long to look at this. The build is failing bc the file is named "deletion-overview" according to the header in the file, but you called it "deletion_overview" in the sidebar.json. Can you fix that and I can merge this?

2025-03-26 12:48 UTC, panta-123 commented
> Hi @panta-123 , sorry it took me this long to look at this. The build is failing bc the file is named "deletion-overview" according to the header in the file, but you called it "deletion_overview" in the sidebar.json. Can you fix that and I can merge this?

DONE and the build is sucess.

2025-03-26 14:26 UTC, voetberg approved these changes

2025-03-26 14:26 UTC, merged