Add rucio secondary software release policy
rucio/documentation pull request #339
Opened 2024-07-02 14:14 UTC by garciagenrique

After discussion with the main developers of the applications
@ftorradeflot, any comment or modification is more than welcome.

Co-authored-by: maany <imptodefeat@gmail.com>

2024-07-03 05:01 UTC, ftorradeflot commented
> After discussion with the main developers of the applications @ftorradeflot, any comment or modification is more than welcome.
> 
> Co-authored-by: maany [imptodefeat@gmail.com](mailto:imptodefeat@gmail.com)

Looks good to me. Thanks @garciagenrique !

2024-07-04 15:39 UTC, rdimaio requested changes

2024-07-04 15:39 UTC, rdimaio commented on docs/started/releasepolicy.md
> +Please refer to the Rucio JypyterLab extension [repository](
```suggestion
Please refer to the Rucio JupyterLab extension [repository](
```

2024-07-04 15:39 UTC, rdimaio commented on docs/started/releasepolicy.md
> +The plugin main dependencies are the Rucio REST API, the JupyterLab environment
```suggestion
The plugin's main dependencies are the Rucio REST API, the JupyterLab environment
```

2024-07-05 08:49 UTC, rdimaio approved these changes

2024-07-15 15:17 UTC, bari12 requested changes
Thanks all. I have some minor adjustments :-)

2024-07-15 15:17 UTC, bari12 commented on docs/started/releasepolicy.md
> +#### Key Technologies
Remove, no need to mention this here.

Also the text above, if we can just link to a rucio-webui page in the doc, we don't need to mention the entire text.

2024-07-15 15:17 UTC, bari12 commented on docs/started/releasepolicy.md
> +#### Versioning
Remove the section, just make it part of the section above

2024-07-15 15:17 UTC, bari12 commented on docs/started/releasepolicy.md
> +  Rucio Server. For example, Rucio Server version 35.x.x is compatible with
... matches that of the Rucio server **it is compatible with**.

2024-07-15 15:17 UTC, bari12 commented on docs/started/releasepolicy.md
> +  Rucio Server. For example, Rucio Server version 35.x.x is compatible with
Also make the version examples bold (like above)

2024-07-15 15:17 UTC, bari12 commented on docs/started/releasepolicy.md
> +The Rucio JupyterLab extension does not follow the relase policy described
Change to: The Rucio Jupyterlab extension follows it's own release policy described below.

2024-07-15 15:17 UTC, bari12 commented on docs/started/releasepolicy.md
> +extension version to install.
Maybe also mention that it will follow semantic versioning.

2024-07-18 09:15 UTC, bari12 approved these changes
Thanks a lot everyone!

2024-07-18 09:16 UTC, merged